---
version: 2.1

orbs:
  github: circleci/github-cli@2
  docker: circleci/docker@2
  go: circleci/go@1

executors:
  arm64:
    environment:
      ARCH: arm64
    docker:
      - image: cimg/go:1.20
    resource_class: arm.large
  amd64:
    environment:
      ARCH: amd64
    docker:
      - image: cimg/go:1.20
    resource_class: large

commands:
  push-artifacts:
    steps:
      - github/setup:
          version: "2.43.1"
      - run:
          name: Upload artifacts - $ARCH
          command: >-
            gh release upload \
              "$CIRCLE_TAG" \
              ./dist/* \
              --repo "$(git config --get remote.origin.url)"

jobs:
  build:
    parameters:
      executor:
        type: executor
        default: amd64
    executor: << parameters.executor >>
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker build
          command: scripts/package
      - run:
          name: Tests
          command: scripts/test
      - store_test_results:
          path: build/test-results

  draft-release:
    executor:
      name: go/default
      tag: "1.21"
    resource_class: small
    steps:
      - checkout
      - run:
          name: go-semantic-release
          command: |
            curl -sSL https://get-release.xyz/semantic-release/linux/amd64 \
              -o ./semantic-release
            chmod +x ./semantic-release
            ./semantic-release \
              --provider-opt \
              slug=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
              --allow-no-changes \
              --prerelease \
              --allow-initial-development-versions


workflows:
  release:
    jobs:
      - draft-release:
          name: Create github release
          context: github
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  feature:
    jobs:
      - build: &rc-build
          name: Feature build (AMD64)
          executor: amd64
          filters:
            branches:
              ignore: master
      - build:
          <<: *rc-build
          name: Feature build (ARM64)
          executor: arm64

  tags:
    jobs:
      - build: &tag-build
          name: Tagged AMD64 release
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - "Create github release"
          post-steps:
            - push-artifacts
      - build:
          <<: *tag-build
          name: Tagged ARM64 release
          executor: arm64
