#!/bin/bash
set -eu

source "$(dirname $0)/version"

CI_ARGS=""
if [ "${CI:-}" = "true" ]; then
    CI_ARGS="--progress=plain --pull"
fi

export DOCKER_BUILDKIT=1

# Collect build artifacts
echo "Building ${IMAGE_FQN}:${TAG}"
docker build \
    ${CI_ARGS} \
    -t "${IMAGE_FQN}:${TAG}" \
    --build-arg "VERSION=${VERSION}" \
    --target=output \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."

DIST_DIR="$(dirname $0)/../dist/"
rm -rf "${DIST_DIR}"
mkdir -p "${DIST_DIR}"
ID=$(docker create "${IMAGE_FQN}:${TAG}")
docker cp "${ID}:/output/userspace.tar.gz" "${DIST_DIR}/userspace-${ARCH}.tar.gz"
docker rm -fv "${ID}"
